### ISSUE TITLE
How to verify it works on a distro - Ubuntu 14.04 in this case?

### ISSUE THREAD

**Issue by hyao** [ronnix/fabtools#263] opened 2014-09-05 15:46 UTC
Hi, 

Thanks for writing such a great tool! In the Readme file, Ubuntu 14.04 is not yet listed as a supported distro. I'm wondering how to verify fabtools work on Ubuntu Trusty?

I ran tox, and got quite a few skipped tests: 
==================== 51 passed, 117 skipped in 2.08 seconds ====================

Guess we need to make all tests pass by installing related dependencies?

Thanks,

**Comment by chrisspen** [comment] 2015-05-07 15:13
I'm also interested in Ubuntu 14.04 support. Any update on this? Has anyone used fabtools on Ubuntu 14.04?

How difficult is it to add support? I'm standardized on 14.04, so I could potentially contribute changes if someone could point me in the right direction.

**Comment by ronnix** [comment] 2015-05-07 16:12
Thanks @hyao and @chrisspen for offering to help!

Running all existing functional tests on a 14.04 Vagrant box should be a good start. Then you could create issues for any failing tests.

You would first need to install Vagrant (see https://www.vagrantup.com/).

Then, to run the tests with Python 2.7 on the official Ubuntu 14.04 image :

```
$ export FABTOOLS_TEST_BOX='ubuntu/trusty64'
$ tox -e py27
```

**Comment by ronnix** [comment] 2015-05-08 15:00
So we have 2 failing tests on Ubuntu 14.04:

```
================================================================== short test summary info ===================================================================
FAIL fabtools/tests/functional_tests/test_apache.py::test_require_site_enabled
FAIL fabtools/tests/functional_tests/test_apache.py::test_apache_can_serve_a_web_page
==================================================== 2 failed, 155 passed, 11 skipped in 1439.02 seconds =====================================================
```

They're both related to Apache, and probably have the same root cause (see issue #253).

**Comment by ronnix** [comment] 2015-05-27 08:29
Fixed in master.

**Closed by ronnix** 2015-05-27 08:29 UTC
Labels: Distro, Tests
